### PR TITLE
Replace exec with hue.js

### PR DESCRIPTION
**Pull request by mattdsteele**
AKA: the _I have no idea if this works_ PR. I was working off the hue-cli source, and think I got it right? But this is straight-up YOLO code until you try it with a real Hue.

All the hue.js code is in `lib/lights.js` and is done via the `register()` and `light()` commands.

There's also new stuff you gotta add in `config.json` - your Hue's IP address, and the light number. I think you have those already? If not, they can be discovered via the hue.js API - just lemme know and I'll tweak it.

Unit tests are available for the new code: just run `npm test`.

Oh yeah, and if you want me to merge this with the image stuff you just did, push your changes and I'll give it a shot!

### CODE REVIEW

**Comment by alexpgates** [comment]
@mattdsteele 
WOW! Nice work! I'm super impressed. Your straight-up YOLO code was spot on. 
I hadn't been using git on my pi, and honestly, I spent more time creating my ssh key and messing around in .bashrc on my pi.

Here's one thing that could make this a bit easier:
When a new app is registered with the hue bridge, I believe hue.js passes along a hashed username along with the appname.

From the readme:

```
Default to a md5 hash based upon the value of the appName configured when calling createClient 
```

(https://github.com/thatguydan/hue.js/blob/master/README.md)

Ideally, after a successful registration with the bridge, it'd be nice to store that username so we can use that on <code>client.register()</code>. If we pass in the username, I think we avoid having to press the button on the hue bridge each time we start the app. I think. But I'm not familiar with the preferred way to save this type of stuff in a config file (http://docs.nodejitsu.com/articles/file-system/how-to-store-local-config-data ?) On top of that, I'm not really clear about where to pass that username in the registration process. : )

Oh! The image stuff is kind of messy. color-thief relies on canvas and there's a lot of crap that I had to go through to actually get that to install. It's still kind of messy, so I'll wait to push that until this sweet syrup is merged in. Cool?

**Comment by mattdsteele** [comment]
Hmm - so right now I've hardcoded the appName as `kitchenlights` in code (line 13 of lights.js), but I could pull it out into the existing config.js so you could tweak it (or have multiple instances running, etc).

What's important for the username? If you just need something idempotent between runs, could you get away with using the default hashed value, and keep the appName consistent? It looks like `hue-cli` uses the default hashed approach (and uses `node-hue-cli` as its appName), for instance.

Alternately, we could always throw a username in config.json and pass it along. And since it's never sent back or modified by the server, we could just add it directly to config.json now and not worry about changing it at runtime. So I think we can sidestep your issue! :feet:

**Comment by alexpgates** [comment]
Yes! If we just store our hashed value in the config and keep the appname consistent, this will allow us to restart the app without having to press the button on the bridge each time.
I'm not concerned about multiple instances running at the same time because the streaming API we're using for Twitter is very clear about this working for one single user and warns very directly against having the same user authed and streaming multiple times.

So, storing the hashed username would absolutely work. Or, like you suggested, adding the username to the config file would also work, too. I think we're fine with keeping <code>kitchenlights</code> in lights.js. 

My understanding is that apps hash these usernames at times to prevent people from possibly trying to use the same username across multiple apps, and as a security measure since one could theoretically make API calls to the bridge if they knew the username. But that kind of security isn't a huge concern for me.

What's easier? Storing that hashed username somewhere retrievable for the app for app restarts down the road _or_ adding the username to the config file? I'm fine with either way. If the degree of difficulty of storing the hashed username isn't that much more than allowing the user to create a username, then we could eliminate that config requirement for the user and be guaranteed a more secure username. 
I'm not sure what goes in to storing that hashed username, though, so I'll let you decide what makes the most sense! : )

In either case, as much detail you could give me about _how_ you implemented this would be great.. I'm a node n00b, clearly!

**Comment by mattdsteele** [comment]
That's the cool thing about Node - it's a culture of inexperience! :trollface: 

The easiest approach is just to throw the unhashed username in the config file, so I just did that. Getting the hashed username would require writing to config files at runtime (which isn't super painful, but it's kind of a hassle if you want to preserve formatting and what not).

And actually, I don't see a way to pull out the username from the hue client, so I'm not sure how you would even get the hashed value. I think you'd have to re-implement the hashing code inside bot.js, and then try to keep it in sync with hue, which just seems like a recipe for disaster.

**Pull request merged**
